/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8;

public class Library {
	
	public static void main(String[] args) {
		System.out.println("HEllo world");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
